### ISSUE TITLE
Fatal Error on Windows Local Machine

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/julia-lite#30]
One of the lead  reviewers from WordPress.org (@kafleg) encounter this error on their local Windows machine:

> Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(C:/xampp/htdocs/theme-review/wp-content/themes/julia-lite/C:/xampp/htdocs/theme-review/wp-content/themes/julia-lite/inc/specific,C:/xampp/htdocs/theme-review/wp-content/themes/julia-lite/C:/xampp/htdocs/theme-review/wp-content/themes/julia-lite/inc/specific): The filename, directory name, or volume label syntax is incorrect. (code: 123) in C:\xampp\htdocs\theme-review\wp-content\themes\julia-lite\components\base\inc\extras.php:459 Stack trace: #0 C:\xampp\htdocs\theme-review\wp-content\themes\julia-lite\components\base\inc\extras.php(459): DirectoryIterator->__construct('C:/xampp/htdocs...') #1 C:\xampp\htdocs\theme-review\wp-content\themes\julia-lite\inc\specific.php(12): pixelgrade_autoload_dir('C:/xampp/htdocs...') #2 C:\xampp\htdocs\theme-review\wp-content\themes\julia-lite\components\base\inc\extras.php(469): require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\theme-review\wp-content\themes\julia-lite\functions.php(202): pixelgrade_aut in C:\xampp\htdocs\theme-review\wp-content\themes\julia-lite\components\base\inc\extras.php on line 459

**Comment by kafleg** [comment]
Follow these things to get the issue,
1. Fresh Install your WordPress
2. Make debug mode true
3. Go to appearance > themes > add new > Julia Lite
4. Install and then activate. 
You will see the above issue there. 

Note: Use Windows and XAMPP server while checking.

**Comment by vladolaru** [comment]
@kafleg Thank you for the pointers. We have managed to replicate the issue and fixed it. It will be included shortly in the v1.1.4 update.
